---
#./ansible-playbook create_project.yml -i env/inventory -e "NAME_PROJECT=myproject" -e "TYPE_PROJECT=cattle"
- hosts: rancher-masters
  gather_facts: no
  roles:
  - {role: create-rancher-project, tags: create-rancher-project}

- hosts: "{{ NAME_PROJECT }}"
  gather_facts: no
  roles:
  - {role: add-host-to-environment, tags: add-host-to-environment}
