---
- include_vars: "{{ inventory_dir }}/group_vars/projects/{{ NAME_PROJECT }}"
- debug: msg="Installing stack {{ STACK_NAME }}"
- name: Create stacks folder for stack {{ STACK_NAME }}
  file: path=stacks/{{STACK_NAME}} state=directory mode=0700
- name: Copy docker-compose for stack {{ STACK_NAME }}
  template: src={{STACK_NAME}}/docker-compose.yml dest=stacks/{{STACK_NAME}}/docker-compose.yml
- name: Copy rancher-compose for stack {{ STACK_NAME }}
  template: src={{STACK_NAME}}/rancher-compose.yml dest=stacks/{{STACK_NAME}}/rancher-compose.yml
- name: Run rancher-compose for stack {{ STACK_NAME }}
  shell: "cd stacks/{{STACK_NAME}} && RANCHER_URL=http://localhost:8080/ RANCHER_ACCESS_KEY={{RANCHER_API_PROJECT_ACCESS_TOKEN}} RANCHER_SECRET_KEY={{RANCHER_API_PROJECT_ACCESS_SECRET}} rancher-compose up -d --upgrade --confirm-upgrade"
  register: stack
  become: yes
- debug: var=stack.stdout_lines
