---
- name: Create docker.service.d directory
  become: yes
  file:
    path: "{{ docker_override_path }}"
    state: directory
  when: docker_override_options

- name: Configure docker
  become: yes
  template:
    src: service_override.conf
    dest: "{{ docker_override_path }}/override.conf"
    owner: root
    mode: 0644
  when: docker_override_options
  notify:
    - reload systemd
    - restart docker

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
