---
- name: Install docker-py
  pip: name=docker-py version="{{dockerpy_version}}"
  become: yes

- name: Add docker apt repo
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
    mode: 644
    state: present
  become: yes


- name: Import the Docker repository key
  apt_key:
    url: https://apt.dockerproject.org/gpg
    id: 2C52609D
    state: present
  become: yes

- name: Install Docker package
  apt:
    name: "{{ docker_package_name }}={{ docker_version }}"
    update_cache: yes
    force: yes
  become: yes
  notify: restart docker

- name: Create a docker group
  group:
    name: docker
    state: present
  become: yes

- name: Add users to docker group
  user: name="{{ item.name}}" groups="docker" shell="/bin/bash" append="yes"
  with_items: '{{ssh_users}}'
  become: yes

- name: Start docker
  service: name=docker state=started
  become: yes

- name: Create docker.service.d directory
  become: yes
  file:
    path: "{{ docker_override_path }}"
    state: directory
  when: docker_override_options

- name: Configure docker
  become: yes
  template:
    src: service_override.conf
    dest: "{{ docker_override_path }}/override.conf"
    owner: root
    mode: 0644
  when: docker_override_options
  notify:
    - restart docker
    - reload systemd

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
