---
- name: Verify if project exists
  stat: path="{{ inventory_dir }}/group_vars/projects/{{ NAME_PROJECT }}.projectkey"
  register: project_file
  delegate_to: localhost

- include: project_cattle.yml
  when: TYPE_PROJECT == 'cattle'

- include: project_kubernetes.yml
  when: TYPE_PROJECT == 'kubernetes'

- include: project_mesos.yml
  when: TYPE_PROJECT == 'mesos'

- name: Create API KEY
  uri:
    method: POST
    status_code: 201
    user: "{{ RANCHER_API_KEY_ACCOUNT_TOKEN }}"
    password: "{{ RANCHER_API_KEY_ACCOUNT_SECRET }}"
    body: ' {"accountId":"{{ PROJECT_ID }}", "name":"{{ NAME_PROJECT}}_key"}'
    HEADER_Accept: "application/json"
    HEADER_Content-Type: "application/json"
    url: http://localhost:{{ RANCHER_MASTER_PORT }}/v1/apikeys
  register: api_key
  when: project_file.stat.exists == False

- name: generate project configuration
  template:  src=files/rancher_project_key.j2 dest={{ inventory_dir }}/group_vars/projects/{{ NAME_PROJECT }}.projectkey
  when: project_file.stat.exists == False
  delegate_to: localhost

- debug: msg="Project apikey generated. You can now vault it with './ansible-vault_wrapper {{ inventory_dir }}/group_vars/projects/{{ NAME_PROJECT }}.projectkey'"
  when: project_file.stat.exists == False
