---
- name: Create Project mesos type
  uri:
    method: POST
    status_code: 201
    user: "{{ RANCHER_API_KEY_ACCOUNT_TOKEN }}"
    password: "{{ RANCHER_API_KEY_ACCOUNT_SECRET }}"
    body: ' {"allowSystemRole":false,"virtualMachine":false,"type":"project","name":"{{ NAME_PROJECT }}","description":"{{ NAME_PROJECT }}","projectTemplateId":"1pt1","projectMembers":[],"created":null,"healthState":null,"kind":null,"removeTime":null,"removed":null,"uuid":null,"version":null,"hostRemoveDelaySeconds":null,"members":[]} '
    HEADER_Accept: "application/json"
    HEADER_Content-Type: "application/json"
    url: http://localhost:{{ RANCHER_MASTER_PORT }}/v2-beta/project
  register: create_project
  when: project_file.stat.exists == False

- debug:
    var: create_project
    verbosity: 2

- name: Register project id
  set_fact:
    PROJECT_ID: "{{ create_project.json['id'] }}"
  when: project_file.stat.exists == False
